# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
apply = ["defer"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.local]
local = "~/.config/zsh"
use = ["{!override,*}.zsh"]

[plugins]
[plugins.base16]
github = 'chriskempson/base16-shell'
apply = ["defer"]
hooks.post = 'source ~/.base16_theme'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
hooks.post = """
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTORY_SUBSTRING_SEARCH_FUZZY=1
HISTORY_SUBSTRING_SEARCH_PREFIXED=1
"""

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.autojump]
github = "wting/autojump"
dir = "bin"
apply = ["PATH", "source", "defer"]

[plugins."z.lua"]
github = "skywind3000/z.lua"
apply = ["defer"]

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["defer"]
[plugins.enhancd.hooks]
post = """
export ENHANCD_FILTER=fzy:fzf:peco
export ENHANCD_DOT_ARG="^"
export ENHANCD_HOME_ARG=""
export ENHANCD_DISABLE_HOME=1
"""
