# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[ -f ${HOME}/.nvm/nvm.sh ] && source ${HOME}/.nvm/nvm.sh

autoload -U compinit
compinit

# use devbox global as a package manager
eval "$(devbox global shellenv --init-hook)"

# use sheldon as a plugin manager
SHELDON_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/sheldon.zsh"
SHELDON_TOML="${XDG_CONFIG_HOME:-$HOME/.config}/sheldon/plugins.toml"
if [[ ! -r "${SHELDON_CACHE}" || "${SHELDON_TOML}" -nt "${SHELDON_CACHE}" ]]; then
  mkdir -p ${XDG_CACHE_HOME:-$HOME/.cache}
  sheldon source > ${SHELDON_CACHE}
fi
source "${SHELDON_CACHE}"
unset SHELDON_CACHE SHELDON_TOML

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
